cube_identifier_params : { 
theta: 3, 
search_radius: 0.015, 
num_vectors: 30,
voxel_grid_x: 0.005,
voxel_grid_y: 0.005,
voxel_grid_z: 0.005,
check_patric_cube: true,
check_purple_cube: false,
size_around_color: 45
}
