cube_identifier_params : { 
theta: 1, 
search_radius: 0.01, 
num_vectors: 100,
voxel_grid_x: 0.008,
voxel_grid_y: 0.008,
voxel_grid_z: 0.008,
check_patric_cube: true,
check_purple_cube: false,
size_around_color: 20
}
